### ISSUE TITLE
Detects thousands of changes on clean install 

### ISSUE THREAD

**Issue by krzkaczor** [maxchehab/quickfix#5]
Hey,
first of all, I would like to say that this is a great project idea :) Unfortunately I didn't get this to work — quickfix detects multiple changes even though I have clean installation (right after doing `yarn`). 

Is this a known issue with yarn? I will try to reproduce it and prepare some smaller example.

**Comment by maxchehab** [comment]
Was the repository created using yarn or npm? Yarn and npm create a lot of different hidden files respective to each other. This may be it.

**Comment by krzkaczor** [comment]
@maxchehab I use solely yarn.

**Comment by maxchehab** [comment]
Ok! Would you mind pointing me to the repository and creating a [gist](http://gist.github.com/) of the changes?

**Comment by phra** [comment]
@maxchehab @krzkaczor i was debugging the same issue.. i think it's related to the fact the `quickfix` doesn't copy the `package.lock` and `yarn.lock` to the temporary directory.. i will send a PR fixing that.

**Comment by phra** [comment]
i confirm that #7 fixes the issue: :shipit:
